source "https://rubygems.org"

gem "tree_support", :path => ".."
gem "static_record", :github => "akicho8/static_record"

gem "rails"
gem "activerecord"
gem "sqlite3"
gem "gviz"
gem "acts_as_tree"
gem "acts_as_list"
gem "byebug"
